package com.sendi.userdb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sendi.userdb.User;
import com.sendi.userdb.RecordData;

import com.sendi.userdb.UserDao;
import com.sendi.userdb.RecordDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig recordDataDaoConfig;

    private final UserDao userDao;
    private final RecordDataDao recordDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recordDataDaoConfig = daoConfigMap.get(RecordDataDao.class).clone();
        recordDataDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        recordDataDao = new RecordDataDao(recordDataDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(RecordData.class, recordDataDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        recordDataDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RecordDataDao getRecordDataDao() {
        return recordDataDao;
    }

}
